
// Objective-C API for talking to the following Go packages
//
//	github.com/0xPolygonID/c-polygonid/cmd/polygonid
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Libpolygonid_FRAMEWORK_H__
#define __Libpolygonid_FRAMEWORK_H__

#include "Polygonid.objc.h"
#include "Universe.objc.h"

#endif
