// Objective-C API for talking to github.com/0xPolygonID/c-polygonid/cmd/polygonid Go package.
//   gobind -lang=objc github.com/0xPolygonID/c-polygonid/cmd/polygonid
//
// File is generated by gobind. Do not edit.

#ifndef __Polygonid_H__
#define __Polygonid_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


// skipped function PLGNAtomicQueryMtpV2Inputs with unsupported parameter or return types


// skipped function PLGNAtomicQueryMtpV2OnChainInputs with unsupported parameter or return types


// skipped function PLGNAtomicQuerySigV2Inputs with unsupported parameter or return types


// skipped function PLGNAtomicQuerySigV2OnChainInputs with unsupported parameter or return types


// skipped function PLGNAuthV2InputsMarshal with unsupported parameter or return types


// skipped function PLGNCalculateGenesisID with unsupported parameter or return types


// skipped function PLGNCreateClaim with unsupported parameter or return types


// skipped function PLGNFreeStatus with unsupported parameter or return types


// skipped function PLGNIDToInt with unsupported parameter or return types


// skipped function PLGNMtpV2Inputs with unsupported parameter or return types


// skipped function PLGNProfileID with unsupported parameter or return types


// skipped function PLGNProofFromSmartContract with unsupported parameter or return types


// skipped function PLGNSigV2Inputs with unsupported parameter or return types


#endif
